@startuml ClimateService_Components
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title "C4 - level3 - Общая схема компонента контроля устройств"

' === Контейнер ===
Container_Boundary(climate_service, "Climate Service (Python)") {

  ' === Ядро сервиса ===
  Component(controller, "Climate Controller", "Основная бизнес-логика HVAC", "прямое управление задает новые параметры, коррекция проводит сравнение текущего и целового состояния (в кэше), и при необходимости производит коррекцию")
  
  ' === Обработка данных ===
  Component(data_filter, "Data Filter", "Фильтрация и валидация данных", "На этапе фильтрации могут детектится сбои и анамалии, и вызывать Emergency Service (логирование происходит там)")

  ' === Работа с хранилищами ===
  Component(redis_client, "Redis Client", "Кеширование текущих значений")
  Component(event_producer, "Kafka Producer", "Отправка событий в Event Bus")
  Component(event_consumer, "Kafka Consumer", "Получение событий датчиков из Event Bus для обработки текущего состояния и коррекции")

  ' === Взаимодействия ===
  event_consumer --> data_filter : "Сырые данные"
  data_filter --> controller : "Очищенные и валидные данные"
  controller --> event_producer : "Команды устройствам"
  controller --> redis_client : "Обновить, получить кеш состояний"
  data_filter --> event_producer : "События для аналитики (агрегирование)"
}

' === Внешние зависимости ===
System_Ext(api_gw, "API Gateway", "KONG")
System_Ext(event_bus, "Event Bus", "Kafka")
System_Ext(redis, "Redis", "Кеш данных")

' === Ключевые связи ===
api_gw --> controller : "Прямые обращения управления от Device Service с параметрами устройств [POST]controls://climate/*\nВ том числе аварийные отключения"

event_bus --> event_consumer  : "данные датчиков"
redis_client --> redis : "R/W"
event_producer --> event_bus : "События"
data_filter --> api_gw : "Экстренные запросы [POST]emergency://*"

@enduml