@startuml ClimateService_Components
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title "C4 - level3 - Общая схема компонентов состояний"

left to right direction

Container_Boundary(State_Service, "State Service") {
    Component(State_Manager, "State Manager", "Настройка конфигураций устройств")
    Component(State_Controller, "State Controller", "Получает конфигурацию и устанавливает значения устройствам")
    Component(Postgres_Client, "Database Client", "Трансляция запросов на язык транзакций")
}

System_Ext(API_GW, "Api-Gateway")
System_Ext(State_Repository, "State Db")


API_GW <--> State_Controller : "принимает [StateId: OperationType]\nотправляет [DeviceId: Value]""
API_GW --> State_Manager : "GET/POST"
State_Manager --> Postgres_Client : "Редактирование конфигураций (заготовленных значений для множества устройств)"
State_Controller --> Postgres_Client : "Получить значения устройств по указанному состоянию"
Postgres_Client --> State_Repository : "SET\SELECT (DeviceId, Value) WHERE StateId = {StateId}"
@enduml